// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTracker.Data;

#nullable disable

namespace SupportTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714043846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SupportTracker.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ahmad bin Ismail",
                            Content = "I checked the logs and it looks like the new auth middleware isn't forwarding CORS headers properly. Digging deeper.",
                            CreatedAt = new DateTime(2026, 7, 14, 9, 45, 0, 0, DateTimeKind.Utc),
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Siti Nurhaliza",
                            Content = "Can we get the design team to prioritize the dark mode color tokens? Blocked on that.",
                            CreatedAt = new DateTime(2026, 7, 13, 9, 30, 0, 0, DateTimeKind.Utc),
                            TicketId = 3
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Ahmad bin Ismail",
                            Content = "Fixed and deployed. Waiting for QA verification.",
                            CreatedAt = new DateTime(2026, 7, 11, 17, 30, 0, 0, DateTimeKind.Utc),
                            TicketId = 4
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Rajesh Kumar",
                            Content = "Implemented using the token bucket algorithm. Each API key tier has its own bucket configuration. PR is up for review.",
                            CreatedAt = new DateTime(2026, 7, 9, 11, 30, 0, 0, DateTimeKind.Utc),
                            TicketId = 5
                        });
                });

            modelBuilder.Entity("SupportTracker.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 1,
                            CreatedAt = new DateTime(2026, 7, 14, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Users are seeing a blank page with 500 error when trying to log in. Started happening after the latest deployment to production. Browser console shows CORS error.",
                            Priority = 3,
                            Status = 0,
                            Title = "Login page returns 500 error after deploy",
                            UpdatedAt = new DateTime(2026, 7, 14, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 7, 13, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "When attempting to export more than 10,000 rows to CSV, the request times out after 30 seconds. Need to implement async streaming or pagination for the export.",
                            Priority = 2,
                            Status = 1,
                            Title = "Export to CSV times out for large datasets",
                            UpdatedAt = new DateTime(2026, 7, 14, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Several customers have requested a dark mode option. The design team has provided the color palette. Need to implement a toggle in user settings and persist the preference.",
                            Priority = 1,
                            Status = 0,
                            Title = "Add dark mode toggle to user settings",
                            UpdatedAt = new DateTime(2026, 7, 12, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssignedToId = 1,
                            CreatedAt = new DateTime(2026, 7, 11, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "The pricing page says 'billed anually' instead of 'billed annually'. Simple text fix needed in the pricing component.",
                            Priority = 0,
                            Status = 2,
                            Title = "Typo on pricing page — 'annually' spelled wrong",
                            UpdatedAt = new DateTime(2026, 7, 11, 17, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AssignedToId = 3,
                            CreatedAt = new DateTime(2026, 7, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Need to implement rate limiting on the public API endpoints to prevent abuse. Should support configurable limits per API key tier (free, pro, enterprise).",
                            Priority = 2,
                            Status = 3,
                            Title = "API rate limiting for third-party integrations",
                            UpdatedAt = new DateTime(2026, 7, 10, 15, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SupportTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Engineering",
                            Email = "ahmad@bassnet.com.my",
                            FullName = "Ahmad bin Ismail"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Support",
                            Email = "siti@bassnet.com.my",
                            FullName = "Siti Nurhaliza"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Engineering",
                            Email = "rajesh@bassnet.com.my",
                            FullName = "Rajesh Kumar"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Product",
                            Email = "meiling@bassnet.com.my",
                            FullName = "Mei Ling Tan"
                        });
                });

            modelBuilder.Entity("SupportTracker.Models.Comment", b =>
                {
                    b.HasOne("SupportTracker.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTracker.Models.Ticket", b =>
                {
                    b.HasOne("SupportTracker.Models.User", "AssignedTo")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");
                });

            modelBuilder.Entity("SupportTracker.Models.Ticket", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SupportTracker.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
